name = "dnsmo-publish"
main = "index.js"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

account_id = "{Cloudflare AccountID}"
workers_dev = true

[env.production]
zone_id = "{Cloudflare ZoneID}"
route = "https://{domain}/*"
vars = { CF_ZONE_ID = "Cloudflare ZoneID", 
CF_API_TOKEN = "Cloudflare API Token", 
WHITELIST_DOMAIN = "Whitelisted Domains", 
USER_REGISTRY_ZONE = "users.customdomain"s }
