name = "dnsmo-worker"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
# Optional: you can pass static configuration here

[[kv_namespaces]]
binding = "DNSMO"
id = "your-kv-id-here"
preview_id = "your-kv-preview-id"
