name = "dnsmo-publish"
main = "index.js"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

account_id = "${CF_ACCOUNT_ID}"
workers_dev = true

[env.production]
zone_id = "${CF_ZONE_ID}"
route = "https://api.example.com/*"

[env.production.vars]
CF_ZONE_ID = "${CF_ZONE_ID}"
CF_API_TOKEN = "${CF_API_TOKEN}"
